services:
  - type: web
    name: project-bolt
    env: node
    nodeVersion: 18.19.0
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: "Project Bolt"
      - key: SECRET_KEY
        sync: false
      - key: WHATSAPP_API_KEY
        sync: false
      - key: WHATSAPP_PHONE_NUMBER
        sync: false
    buildFilter:
      paths:
        - src/**
        - package.json
        - vite.config.ts
        - tsconfig.json
        - index.html
